#!/usr/bin/env bash
# claude/bootstrap.sh — reproduce this setup for Claude Code on a fresh machine.
# Generated by sync.mjs. Review before running. (Claude Code-specific.)
set -euo pipefail

CLAUDE_DIR="${HOME}/.claude"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"   # the claude/ dir
REPO="$(cd "${HERE}/.." && pwd)"                        # repo root

echo "==> Installing global rules"
mkdir -p "${CLAUDE_DIR}"
cp "${REPO}/rules/coding-guidelines.md" "${CLAUDE_DIR}/CLAUDE.md"

echo "==> Installing settings (review paths/env first)"
cp "${HERE}/settings.json" "${CLAUDE_DIR}/settings.json"

echo "==> Installing portable skills + Claude hooks"
[ -d "${REPO}/skills" ] && cp -R "${REPO}/skills/." "${CLAUDE_DIR}/skills/" || true
[ -d "${HERE}/hooks" ]  && cp -R "${HERE}/hooks/."  "${CLAUDE_DIR}/hooks/"  || true

echo "==> Adding plugin marketplaces"
claude plugin marketplace add "anthropics/claude-plugins-official"   # claude-plugins-official
claude plugin marketplace add "https://github.com/affaan-m/ECC.git"   # ecc
claude plugin marketplace add "EveryInc/compound-engineering-plugin"   # compound-engineering-plugin
claude plugin marketplace add "warpdotdev/claude-code-warp"   # claude-code-warp

echo "==> Installing plugins"
claude plugin install "superpowers@claude-plugins-official"
claude plugin install "warp@claude-code-warp"

echo "==> MCP servers: copy mcp/servers.json into your client and supply env vars"
echo "    See .env.example for required secrets (sentry, linear, ...)."
echo
echo "Done. get-shit-done is installed separately — see claude/plugins.json."
