#!/usr/bin/env bash
# bootstrap.sh — reproduce this agent setup on a fresh machine.
# Generated by sync.mjs. Review before running.
set -euo pipefail

CLAUDE_DIR="${HOME}/.claude"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "==> Installing global rules"
mkdir -p "${CLAUDE_DIR}"
cp "${HERE}/rules/CLAUDE.md" "${CLAUDE_DIR}/CLAUDE.md"

echo "==> Installing settings (review paths/env first)"
cp "${HERE}/settings/settings.json" "${CLAUDE_DIR}/settings.json"

echo "==> Installing authored skills/hooks"
[ -d "${HERE}/skills" ] && cp -R "${HERE}/skills/." "${CLAUDE_DIR}/skills/" || true
[ -d "${HERE}/hooks" ]  && cp -R "${HERE}/hooks/."  "${CLAUDE_DIR}/hooks/"  || true

echo "==> Adding plugin marketplaces"
claude plugin marketplace add "anthropics/claude-plugins-official"   # claude-plugins-official
claude plugin marketplace add "https://github.com/affaan-m/ECC.git"   # ecc
claude plugin marketplace add "EveryInc/compound-engineering-plugin"   # compound-engineering-plugin
claude plugin marketplace add "warpdotdev/claude-code-warp"   # claude-code-warp

echo "==> Installing plugins"
claude plugin install "superpowers@claude-plugins-official"
claude plugin install "ecc@ecc"
claude plugin install "compound-engineering@compound-engineering-plugin"
claude plugin install "warp@claude-code-warp"

echo "==> MCP servers: copy mcp/servers.json into your client and supply env vars"
echo "    See .env.example for required secrets (sentry, linear, ...)."
echo
echo "Done. get-shit-done is installed separately — see plugins/manifest.json."
